### ISSUE TITLE
Suggestions for setting font family?

### ISSUE THREAD

**Issue by brandondurham** [webdeveloperpr/draft-js-custom-styles#11]
It seems to be missing from most of the Draft.js-related documentation I’m finding, yet is one of the more common setting people tend to use.

I’m working on a type testing tool that requires a “font” feature where you can choose the font you’d like applied to the selected text. There will most definitely be lots of overlapping selections. Any recommendations on how to pull this off?

**Comment by betancourtl** [comment]
If you go to this link. https://webdeveloperpr.github.io/draft-js-custom-styles/ and see the toggle functionality. You might be able to re-create the same behavior with using a select dropdown. Each Select Option could be a font-family

**Comment by brandondurham** [comment]
Very nice. Is the source code posted anywhere?
