### ISSUE TITLE
Toggle style with nothing selected seems not work

### ISSUE THREAD

**Issue by samotoo** [webdeveloperpr/draft-js-custom-styles#3]
Hi,
Thank you very much for this wonderful lib.

I tried to use it to toggle the color. It works great if I have selected some text in the editor, but if I don't select any text, it seems the style cannot be toggled. Is there any solution to resolve this? Or am I doing anything incorrectly?

Thanks.

**Comment by betancourtl** [comment]
In order for styles to be applied there needs to be a selection.
if you select the word hello and then toggle the styles it should add/remove the styles, to the selected text

```
v start offset
hello world
....^ end offset
```
If there is no selection then you won't be able to toggle the styles.

**Comment by samotoo** [comment]
Thanks for the response. I understand your point. However, I tried to define a custom style map and use `RichUtils.toggleInlineStyle` to toggle the style, it just worked even there is no text selection, I mean, the style is applied to the new text I input.

**Comment by betancourtl** [comment]
I'm a bit confused as to what your expected behavior is. I believe that you are trying to continue the styles as you type? 

Is this the expected behavior?

1. Select some text
2. Make a text selection
3. Toggle Styles
4. With the cursor at the end of the selection keep writing
5. expect the style to continue being applied the the newly inputted text?

**Comment by samotoo** [comment]
My expected behavior is as follows:

1. Focus the cursor to the editor
2. Input some text, old styles are applied
3. No text select, just leave the cursor at the end of text
4. Toggle to new styles
3. Continue typing, expect the new styles applied to the newly inputted text.

I hope that is clear.

**Comment by betancourtl** [comment]
Ok that makes sense. Here is how the toggleInlineStyle function from draft-js works.

1. When the selection is collapsed it should toggle the inlineStyleOverride. When the inlineStyle override is set to true it should apply the styles to the next typed characters.

2. When the selection is not collapsed it should apply/remove the inline style.

I believe  behavior 2 is the one that `draft-js-custom-styles` is supporting right now, but you would like to include behavior 1 as part of the toggle function?

Here is a reference to the original draft-js toggle function

```javascript
  toggleInlineStyle: function toggleInlineStyle(editorState, inlineStyle) {
    var selection = editorState.getSelection();
    var currentStyle = editorState.getCurrentInlineStyle();

    // If the selection is collapsed, toggle the specified style on or off and
    // set the result as the new inline style override. This will then be
    // used as the inline style for the next character to be inserted.
    if (selection.isCollapsed()) {
      return EditorState.setInlineStyleOverride(editorState, currentStyle.has(inlineStyle) ? currentStyle.remove(inlineStyle) : currentStyle.add(inlineStyle));
    }

    // If characters are selected, immediately apply or remove the
    // inline style on the document state itself.
    var content = editorState.getCurrentContent();
    var newContent;

    // If the style is already present for the selection range, remove it.
    // Otherwise, apply it.
    if (currentStyle.has(inlineStyle)) {
      newContent = DraftModifier.removeInlineStyle(content, selection, inlineStyle);
    } else {
      newContent = DraftModifier.applyInlineStyle(content, selection, inlineStyle);
    }

    return EditorState.push(editorState, newContent, 'change-inline-style');
  },
```

**Comment by samotoo** [comment]
So will you plan to include behavior 1 in `draft-js-custom-styles`?

**Comment by betancourtl** [comment]
I think it would be good idea to add it just so we can keep the same draft-js functionality.

**Comment by betancourtl** [comment]
Let me stash my changes, I think I can get this feature working pretty quick tonight.

**Comment by samotoo** [comment]
Thank you soooooo much! You are soooooooo kind! I'll try immediately when the feature is ready.

**Comment by betancourtl** [comment]
You can check it out now.

**Comment by betancourtl** [comment]
I tested on my machine and it worked fine.  If you find any issues let me know.

**Comment by samotoo** [comment]
Hi,

Updated to 2.0.0 and I think there might still be an issue there. 

Check file `draft-js-custom-styles/src/index.js`, line 92-94, assume I want to toggle color to red.

1. At first, `currentStyle` is empty, and style will be added, so `styleOverride` should turns to `COLOR_red`.
2. Then I toggle the color to blue, now `currentStyle` is not empty but it doesn't contain `COLOR_blue`, then the new style is added, now `styleOverride` contains both `COLOR_red` and `COLOR_blue`. Now I find out that `COLOR_red` is still taking effect.

Selected text doesn't suffer from this issue, I think it is because at line 99 all styles with the prefix (in this example, COLOR_) are removed. Please help to evaluate.

Thanks!

**Comment by betancourtl** [comment]
Ahh good catch, Taking a look.

**Comment by betancourtl** [comment]
I fixed the issue I believe the the behavior is correct now, please check it out here thx!
https://webdeveloperpr.github.io/draft-js-custom-styles/

**Comment by samotoo** [comment]
Just updated to 2.0.1 and it works like a charm! Thank you!

**Comment by tbleckert** [comment]
Hi! First of all, thanks! Really glad I found this, has helped a lot.

I'm not getting this to work properly. This only works with `toggle`, and `toggle` works great with buttons when you actually want to toggle the color, but if you have a colorpicker you get a flicker since every other toggle removes the color. I found that `add` works better with colorpickers or am I doing something wrong?

So currently I need to have this (still causing a flicker though):

```js
if (!selection.isCollapsed()) {
   styles.color.add(this.state.editorState, color);
} else {
   styles.color.toggle(this.state.editorState, color);
}
```

**Comment by betancourtl** [comment]
If you are creating a color picker then it's probably best to use the add fn. Here is an example of a color picker that I did a while ago.

https://webdeveloperpr.github.io/draft-js-color-picker/

Here is the repo:
https://github.com/webdeveloperpr/draft-js-color-picker

**Comment by tbleckert** [comment]
Yes, but the add function doesn't work with collapsed selections. Not from what I can see, but maybe I did something wrong. As you see in the code example I had to check selection state to decide between toggle and add.

**Comment by betancourtl** [comment]
Can you describe the expected behavior when selection is collapsed and when selection is not collapsed?

I believe this is the current behavior right now when using add fn.

### non-collapsed
- User makes a selection.
- User clicks on a color.
- Text changes color for the selected text.

### collapsed
- Editor has focus and the cursor is collapsed
- User clicks on a color
- Nothing happens because there is no selection made.

**Comment by tbleckert** [comment]
Yes, that's the expected behavior, except that it only works with toggle, not add. But if `add` is supposed to handle collapsed states as well, then there's something wrong on my end.

**Comment by betancourtl** [comment]
add fn does not handle collapsed states (when the startOffset and the endOffset are the same) and you use the add fn. There is nothing selected so add fn cannot apply the color.

**Comment by betancourtl** [comment]
```javascript
const addStyle = prefix => (editorState, style) => {
  const newContentState = Modifier.applyInlineStyle(
    editorState.getCurrentContent(),
    editorState.getSelection(),
    prefix + style
  );
  return EditorState.push(editorState, newContentState, 'change-inline-style');
};

const removeStyle = prefix => editorState => {
  return mapSelectedCharacters(filterDynamicStyle(prefix))(editorState);
};

// This is the actual add fn() that gets exported.
const removeAndAdd = prefix => (editorState, style) => {
  return addStyle(prefix)(removeStyle(prefix)(editorState), style);
};
```

**Comment by betancourtl** [comment]
To add style we use the Modifier.applyInlineStyle function from draft-js. So the behavior should be equal to `draft-js`

**Comment by tbleckert** [comment]
Ok cool, thanks for the explanation. And again, great job with this, works perfectly!

**Comment by shreyanshsing** [comment]
> ```js
> const addStyle = prefix => (editorState, style) => {
>   const newContentState = Modifier.applyInlineStyle(
>     editorState.getCurrentContent(),
>     editorState.getSelection(),
>     prefix + style
>   );
>   return EditorState.push(editorState, newContentState, 'change-inline-style');
> };
> 
> const removeStyle = prefix => editorState => {
>   return mapSelectedCharacters(filterDynamicStyle(prefix))(editorState);
> };
> 
> // This is the actual add fn() that gets exported.
> const removeAndAdd = prefix => (editorState, style) => {
>   return addStyle(prefix)(removeStyle(prefix)(editorState), style);
> };
> ```

can you please suggest me what is the syntax to change font family , that prefix what should be there ('FONTFAMILY','fontFamily') like I am just doing it for a project so don't want to dive deeper.

**Comment by nikolai-smolianinov** [comment]
> Ok that makes sense. Here is how the toggleInlineStyle function from draft-js works.
> 
> 1. When the selection is collapsed it should toggle the inlineStyleOverride. When the inlineStyle override is set to true it should apply the styles to the next typed characters.
> 2. When the selection is not collapsed it should apply/remove the inline style.
> 
> I believe behavior 2 is the one that `draft-js-custom-styles` is supporting right now, but you would like to include behavior 1 as part of the toggle function?
> 
> Here is a reference to the original draft-js toggle function
> 
> ```js
>   toggleInlineStyle: function toggleInlineStyle(editorState, inlineStyle) {
>     var selection = editorState.getSelection();
>     var currentStyle = editorState.getCurrentInlineStyle();
> 
>     // If the selection is collapsed, toggle the specified style on or off and
>     // set the result as the new inline style override. This will then be
>     // used as the inline style for the next character to be inserted.
>     if (selection.isCollapsed()) {
>       return EditorState.setInlineStyleOverride(editorState, currentStyle.has(inlineStyle) ? currentStyle.remove(inlineStyle) : currentStyle.add(inlineStyle));
>     }
> 
>     // If characters are selected, immediately apply or remove the
>     // inline style on the document state itself.
>     var content = editorState.getCurrentContent();
>     var newContent;
> 
>     // If the style is already present for the selection range, remove it.
>     // Otherwise, apply it.
>     if (currentStyle.has(inlineStyle)) {
>       newContent = DraftModifier.removeInlineStyle(content, selection, inlineStyle);
>     } else {
>       newContent = DraftModifier.applyInlineStyle(content, selection, inlineStyle);
>     }
> 
>     return EditorState.push(editorState, newContent, 'change-inline-style');
>   },
> ```

Dude, you are my hero.
