### ISSUE TITLE
Styles Do Not Apply On Collapsed Selection State

### ISSUE THREAD

**Issue by gdad-s-river** [webdeveloperpr/draft-js-custom-styles#4]
Since `Modifier.applyInlineStyles` is used to modify the inline styles,  I think for this reason the styles aren't applied if the selection state is collapsed. For example, in this [poetry editor](https://www.youtube.com/watch?v=AWs_p4z9OKA&t=5s) that I'm coding up, when I change the slider and use `draft-js-custom-styles` to change the inline styles (font size), it only works if some text is selected. 

My intended behaviour is that, even if nothing is selected (collapsed selection state), then also the inline styles should be applied to the character that will be entered there after (I think `RichUtils.toggleInlineStyles` does that). Any idea how could I do that ?

Thanks!

**Comment by betancourtl** [comment]
Hi thx for posting, which method are you using to apply the styles?

**Comment by gdad-s-river** [comment]
[`addFontSize`](https://github.com/gdad-s-river/poetry-editor/blob/4fc9493998ed06d8ee3da39a4dad7b3a24407496/src/components/FontSizeChanger.js#L18) [initiated](https://github.com/gdad-s-river/poetry-editor/blob/4fc9493998ed06d8ee3da39a4dad7b3a24407496/src/PoetryEditor.js#L25) with [color picker util](https://github.com/gdad-s-river/poetry-editor/blob/feature/layout-rewrite/src/utils/colorPickerUtil.js)

Reproducing steps to see it in action : 

1. clone the repo
2. checkout `layout-rewrite` branch
3. npm install / yarn
4. npm/yarn start

**Comment by betancourtl** [comment]
Ok awesome. That one does not add the inlineStyleOverride. It uses the draft-js API to set it.
I might be able to modify  it so you can apply the override to collapsed/non-collapsed .

**Comment by gdad-s-river** [comment]
@webdeveloperpr, it'd be really cool if you could do that :) , because I'd been struggling on how to :D

**Comment by betancourtl** [comment]
I'll see if I can get it working tonight, and send you a link to an example so you can check it out.

**Comment by gdad-s-river** [comment]
That'd be nice, thank you so much 😊

**Comment by gdad-s-river** [comment]
@webdeveloperpr anytime you could would be fine really. Whenever you are not occupied.

**Comment by jpuri** [comment]
@gdad-s-river : There can be 2 fixes:
1. You can try to change current selection to include whole block and then call toggle style, draft has method to setSelection, and then you can reset it back to collapsed state.
2. Instead of changing inline styles you add a block level meta-data for this property and then use it to style the block.

**Comment by betancourtl** [comment]
@gdad-s-river I added the changes to the repo and tested out your `layout-rewrite` branch using `draft-js-custom-styles@2.0.2`. Collapsed style now have inlineStyleOverrides added  when using `add()`.

![color](https://user-images.githubusercontent.com/7534346/34926418-3c4ba1a8-f97d-11e7-98d4-713aecc93273.gif)

**Comment by betancourtl** [comment]
Also @jpuri thx for suggestions!

**Comment by gdad-s-river** [comment]
@webdeveloperpr thanks a lot for being so quick on the request. Really appreciate it 😃
