### ISSUE TITLE
Why are property values lowercase?

### ISSUE THREAD

**Issue by rpellerin** [webdeveloperpr/draft-js-custom-styles#6]
Hi,
In https://github.com/webdeveloperpr/draft-js-custom-styles/blob/master/src/index.js#L226, why is `match[2]` transformed into lowercase?
This is causing issues when dealing font font-family names.
If there's no reason behind, I will happily submit a PR to change that.

**Comment by betancourtl** [comment]
Hey! I think your are right. There should be no reason for the value to be lowercased. Right now if a someone adds a font-family of lets say `fontAwesome`.  Then the exported value will end up being `fontawesome`. Feel free to submit a PR with tests and I can merge and push to NPM.
